---
- name: Create Groups homeassistant
  ansible.builtin.group:
    name: "{{ ha_group }}"
    system: true

- name: Create user and add to group
  ansible.builtin.user:
    name: "{{ ha_user }}"
    group: "{{ ha_group }}"
    comment: "Home Assistant"
    createhome: true
    system: true
