---
- name: Install systemd unit file
  ansible.builtin.template:
    src: homeassistant.service.j2
    dest: "/etc/systemd/system/homeassistant.service"
    owner: root
    group: root
    mode: 0644
  notify: 
  - "Start Home Assistant"


