---
# tasks to install required packages for Home Assistant
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install specific OS packages
  ansible.builtin.package:
    name: libtiff6
    state: present
  when: ansible_distribution == "Debian"

- name: Install specific packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-dev
    - python3-venv
    - python3-pip
    - bluez
    - libffi-dev
    - libssl-dev
    - libjpeg-dev
    - zlib1g-dev
    - autoconf
    - build-essential
    - libopenjp2-7
    - libturbojpeg0-dev
    - tzdata
    - ffmpeg
    - liblapack3
    - liblapack-dev
    - libatlas-base-dev

- name: Install Debian-required additional pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    executable: pip3
  with_items:
    - appdirs
    - packaging
    - wheel
    - aiohttp_cors
  when: ansible_os_family == "Debian"
